services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"  # endpoint unificado
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack
      - LOCALSTACK_HOST=localstack
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - ./localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - localstack_network
  aws-cli:
    image: amazon/aws-cli
    container_name: aws_cli
    entrypoint: /bin/sh -c "while sleep 3600; do :; done"
    volumes:
      - ./repo:/repo
    networks:
      - localstack_network
    depends_on:
      - localstack
networks:
  localstack_network:
    driver: bridge
